Changed from field injection to constructor injection
sabaubogdan/easytracking pull request #1
Opened 2018-01-04 22:14 UTC by sabaubogdan

2018-01-05 11:23 UTC, DavidArt commented
looks ok. you can do the merge

2018-01-05 19:22 UTC, sabaudragos requested changes

2018-01-05 19:22 UTC, Callin commented on src/main/java/xyz/vegaone/easytracking/config/EasyTrackConfig.java
For some reason I cannot comment on line 14th, but you have a field injection there. Could you please switch to constructor based injection?

2018-01-05 19:22 UTC, Callin commented on src/main/java/xyz/vegaone/easytracking/service/ProjectService.java
There are some unused imports in this class and some commented code at line 53, could you please remove them?

2018-01-05 19:22 UTC, Callin commented on src/test/java/xyz/vegaone/easytracking/project/ProjectServiceTest.java
> +
This class has some unused imports and commented code as well. Could you please remove them?

2018-01-06 16:39 UTC, sabaudragos approved these changes

2018-01-06 19:11 UTC, merged