Create endpoint for Project
sabaubogdan/easytracking pull request #13
Opened 2018-01-09 21:21 UTC by DavidArt

2018-01-09 23:19 UTC, sabaudragos requested changes

2018-01-09 23:19 UTC, sabaudragos commented on src/main/java/xyz/vegaone/easytracking/controller/ProjectController.java
> +    @ResponseStatus(HttpStatus.OK)
`HttpStatus.OK` is the default status used by Spring MVC. So it can be removed, Spring will use it anyway

2018-01-10 08:14 UTC, DavidArt commented on src/main/java/xyz/vegaone/easytracking/controller/ProjectController.java
> +    @ResponseStatus(HttpStatus.OK)
ok team lead

2018-01-10 18:42 UTC, sabaudragos approved these changes

2018-01-10 19:20 UTC, merged